"""upgrade_cithun

迁移 ID: e5927f73764b
父迁移: d7f57cd387ff
创建时间: 2025-12-15 13:30:51.575940

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = "e5927f73764b"
down_revision: str | Sequence[str] | None = "d7f57cd387ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_permission_resourcemodel",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("parent_id", sa.String(length=256), nullable=True),
        sa.Column("inherit_mode", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["nonebot_plugin_permission_resourcemodel.id"],
            name=op.f("fk_nonebot_plugin_permission_resourcemodel_parent_id_nonebot_plugin_permission_resourcemodel"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_resourcemodel")),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_rolemodel",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_rolemodel")),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_trackmodel",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_trackmodel")),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_usermodel",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_usermodel")),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_aclentrymodel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_type", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=256), nullable=False),
        sa.Column("allow_mask", sa.Integer(), nullable=False),
        sa.Column("deny_mask", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["nonebot_plugin_permission_resourcemodel.id"],
            name=op.f("fk_nonebot_plugin_permission_aclentrymodel_resource_id_nonebot_plugin_permission_resourcemodel"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_aclentrymodel")),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_roleinheritsmodel",
        sa.Column("role_id", sa.String(length=64), nullable=False),
        sa.Column("parent_role_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["nonebot_plugin_permission_rolemodel.id"],
            name=op.f(
                "fk_nonebot_plugin_permission_roleinheritsmodel_parent_role_id_nonebot_plugin_permission_rolemodel"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["nonebot_plugin_permission_rolemodel.id"],
            name=op.f("fk_nonebot_plugin_permission_roleinheritsmodel_role_id_nonebot_plugin_permission_rolemodel"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id",
            "parent_role_id",
            name=op.f("pk_nonebot_plugin_permission_roleinheritsmodel"),
        ),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_tracklevelmodel",
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.String(length=256), nullable=False),
        sa.Column("role_id", sa.String(length=64), nullable=False),
        sa.Column("level_name", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["nonebot_plugin_permission_rolemodel.id"],
            name=op.f("fk_nonebot_plugin_permission_tracklevelmodel_role_id_nonebot_plugin_permission_rolemodel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["nonebot_plugin_permission_trackmodel.id"],
            name=op.f("fk_nonebot_plugin_permission_tracklevelmodel_track_id_nonebot_plugin_permission_trackmodel"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "track_id",
            "role_id",
            name=op.f("pk_nonebot_plugin_permission_tracklevelmodel"),
        ),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_userrolesmodel",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["nonebot_plugin_permission_rolemodel.id"],
            name=op.f("fk_nonebot_plugin_permission_userrolesmodel_role_id_nonebot_plugin_permission_rolemodel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["nonebot_plugin_permission_usermodel.id"],
            name=op.f("fk_nonebot_plugin_permission_userrolesmodel_user_id_nonebot_plugin_permission_usermodel"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "role_id",
            name=op.f("pk_nonebot_plugin_permission_userrolesmodel"),
        ),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.create_table(
        "nonebot_plugin_permission_acldependencymodel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("acl_id", sa.Integer(), nullable=False),
        sa.Column("dep_subject_type", sa.String(length=16), nullable=False),
        sa.Column("dep_subject_id", sa.String(length=64), nullable=False),
        sa.Column("dep_resource_id", sa.String(length=256), nullable=False),
        sa.Column("required_mask", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["acl_id"],
            ["nonebot_plugin_permission_aclentrymodel.id"],
            name=op.f("fk_nonebot_plugin_permission_acldependencymodel_acl_id_nonebot_plugin_permission_aclentrymodel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dep_resource_id"],
            ["nonebot_plugin_permission_resourcemodel.id"],
            name=op.f(
                "fk_nonebot_plugin_permission_acldependencymodel_dep_resource_id_nonebot_plugin_permission_resourcemodel"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_acldependencymodel")),
        info={"bind_key": "nonebot_plugin_permission"},
    )
    op.drop_table("nonebot_plugin_permission_ownerpermissionmodel")
    op.drop_table("nonebot_plugin_permission_dependencymodel")
    op.drop_table("nonebot_plugin_permission_ownermodel")
    op.drop_table("nonebot_plugin_permission_ownerinheritsmodel")
    op.drop_table("nonebot_plugin_permission_permissionmodel")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_permission_permissionmodel",
        sa.Column("name", sa.VARCHAR(length=512), nullable=False),
        sa.Column("subs", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", name="pk_nonebot_plugin_permission_permissionmodel"),
    )
    op.create_table(
        "nonebot_plugin_permission_ownerinheritsmodel",
        sa.Column("owner_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("inherits_name", sa.VARCHAR(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["inherits_name"],
            ["nonebot_plugin_permission_ownermodel.name"],
            name=op.f(
                "fk_nonebot_plugin_permission_ownerinheritsmodel_inherits_name_nonebot_plugin_permission_ownermodel"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_name"],
            ["nonebot_plugin_permission_ownermodel.name"],
            name=op.f(
                "fk_nonebot_plugin_permission_ownerinheritsmodel_owner_name_nonebot_plugin_permission_ownermodel"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "owner_name",
            "inherits_name",
            name=op.f("pk_nonebot_plugin_permission_ownerinheritsmodel"),
        ),
    )
    op.create_table(
        "nonebot_plugin_permission_ownermodel",
        sa.Column("name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("priority", sa.INTEGER(), nullable=True),
        sa.Column("wildcards", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", name="pk_nonebot_plugin_permission_ownermodel"),
    )
    op.create_table(
        "nonebot_plugin_permission_dependencymodel",
        sa.Column("name", sa.VARCHAR(length=512), nullable=False),
        sa.Column("subs", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_nonebot_plugin_permission_dependencymodel")),
    )
    op.create_table(
        "nonebot_plugin_permission_ownerpermissionmodel",
        sa.Column("owner_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("permission", sa.VARCHAR(length=512), nullable=False),
        sa.Column("state", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_name"],
            ["nonebot_plugin_permission_ownermodel.name"],
            name=op.f(
                "fk_nonebot_plugin_permission_ownerpermissionmodel_owner_name_nonebot_plugin_permission_ownermodel"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission"],
            ["nonebot_plugin_permission_permissionmodel.name"],
            name=op.f(
                "fk_nonebot_plugin_permission_ownerpermissionmodel_permission_nonebot_plugin_permission_permissionmodel"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "owner_name",
            "permission",
            name=op.f("pk_nonebot_plugin_permission_ownerpermissionmodel"),
        ),
    )
    op.drop_table("nonebot_plugin_permission_acldependencymodel")
    op.drop_table("nonebot_plugin_permission_userrolesmodel")
    op.drop_table("nonebot_plugin_permission_tracklevelmodel")
    op.drop_table("nonebot_plugin_permission_roleinheritsmodel")
    op.drop_table("nonebot_plugin_permission_aclentrymodel")
    op.drop_table("nonebot_plugin_permission_usermodel")
    op.drop_table("nonebot_plugin_permission_trackmodel")
    op.drop_table("nonebot_plugin_permission_rolemodel")
    op.drop_table("nonebot_plugin_permission_resourcemodel")
    # ### end Alembic commands ###
